### ISSUE TITLE
Kademlia findBest crash on toynet server nodes

### ISSUE THREAD

**Issue by dob** [livepeer/livepeer-swarm#17]
Need to look into the cause of this...

panic: runtime error: index out of range

goroutine 48 [running]:
panic(0xe94540, 0xc82000e080)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/livepeer/go-livepeer/vendor/github.com/ethereum/go-ethereum/swarm/network/kademlia.(*KadDb).findBest(0xc820084cf0, 0x4, 0xc821381d38, 0x0, 0xc820111301, 0x0)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/ethereum/go-ethereum/swarm/network/kademlia/kaddb.go:206 +0x1a56
github.com/livepeer/go-livepeer/vendor/github.com/ethereum/go-ethereum/swarm/network/kademlia.(*Kademlia).Suggest(0xc820058900, 0x0, 0xc821381d00, 0x0)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/vendor/github.com/ethereum/go-ethereum/swarm/network/kademlia/kademlia.go:297 +0xbf
github.com/livepeer/go-livepeer/livepeer/network.(*Hive).Start.func1(0xc8201644d0, 0xc8202217a0)
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/livepeer/network/hive.go:145 +0xaf
created by github.com/livepeer/go-livepeer/livepeer/network.(*Hive).Start
        /home/ubuntu/go/src/github.com/livepeer/go-livepeer/livepeer/network/hive.go:178 +0x33c

**Comment by dob** [comment]
Haven't seen this again since code overhaul.
